### ISSUE TITLE
Expand terminology for metadata

### ISSUE THREAD

**Issue by grische** [Remedy-Entertainment/USDBook#10]
The metadata [src/terminology/metadata.md](https://github.com/Remedy-Entertainment/USDBook/blob/main/src/terminology/metadata.md) file is a bit sparse. It would be great if there were some more hands-on examples of when metadata can be used for example.

**Comment by kminnaert** [comment]
Apologies for the delay! I'll tackle this when I get the chance!

**Comment by kminnaert** [comment]
@grische I created a draft PR if you want to take a look and see if it is what you had in mind.
